spring.application.name=newPath

# Correct JDBC URL format: jdbc:postgresql://host:port/database
spring.datasource.url=jdbc:postgresql://localhost:5432/CrudOps
spring.datasource.username=postgres
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update

# optional - change default swagger-ui path
springdoc.swagger-ui.path=/swagger-ui.html

# optional - change api-docs path (default is /v3/api-docs)
# springdoc.api-docs.path=/v3/api-docs
    